apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: snapshot-policy
  namespace: kasten-io
spec:
  actions:
    - action: backup
  frequency: '@onDemand'
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - backup-test
