apiVersion: apik10.kasten.io/v1alpha1
kind: K10
metadata:
  name: k10
  namespace: kasten-io
spec:
  auth:
    basicAuth:
      enabled: false
    tokenAuth:
      enabled: true
  route:
    enabled: true
    tls:
      enabled: true
  scc:
    create: true
  tls:
    enabled: true